#cloud-config
repo_update: true
repo_upgrade: security
package_upgrade: true
packages:
  - nvme-cli
  - awscli
  - zip
runcmd:
  - set -e
  - mkdir -p /opt/conf
  - aws s3 cp s3://${s3_bucket}/conf/conf.zip /opt/conf
  - curl -L "https://www.factorio.com/get-download/${factorio_version}/headless/linux64" -o /opt/factorio.tar.gz
  - $(cd /opt/conf && unzip conf.zip && bash ./install.bash)
